import argparse
import os

from models.CCO import CCO
from utils.to_txt import TO_TXT
from utils.to_vtk import TO_VTK

def main():
    parser = argparse.ArgumentParser(
        description="This Python project converts .xml files generated by the OpenCCO project "
                    "(https://github.com/OpenCCO-team/OpenCCO) into both .txt and .vtk formats."
    )

    parser.add_argument("input", type=str, help="Path to .xml input file")
    parser.add_argument("--txt", nargs="?", const="output.txt", default=None, help="Optional path to .txt output file (default: 'output.txt' if flag is used without value)")
    parser.add_argument("--vtk", nargs="?", const="output.vtk", default=None, help="Optional path to .vtk output file (default: 'output.vtk' if flag is used without value)")

    args = parser.parse_args()

    if not os.path.exists(args.input):
        raise FileNotFoundError(f"ERROR: The file '{args.input}' was not found.")

    if not args.input.lower().endswith(".xml"):
        raise ValueError(f"ERROR: The input file must be an .xml file. Given: '{args.input}'")

    cco = CCO(args.input)

    if args.txt:
        if not args.txt.lower().endswith(".txt"):
            raise ValueError(f"ERROR: The txt output file must be an .txt file. Given: '{args.txt}'")

        to_txt = TO_TXT(cco, args.txt)
    else:
        to_txt = TO_TXT(cco)

    if args.vtk:
        if not args.vtk.lower().endswith(".vtk"):
            raise ValueError(f"ERROR: The vtk output file must be an .vtk file. Given: '{args.vtk}'")

        to_vtk = TO_VTK(cco, args.vtk)
    else:
        to_vtk = TO_VTK(cco)

if __name__ == '__main__':
    main()
